config/routes.rb
AlumniKickstarter::Application.routes.draw do
  resources :students

root :to => 'students#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlumniKickstarter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
  <!DOCTYPE html>  
  <html>
  <head>
    <title>Raise money by engaging students and alumni</title>
    <!--[if lt IE 9]>  
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->  

    <%= stylesheet_link_tag    "application", :media =>  
    "all" %>
    <%= javascript_include_tag "application" %>  
    <%= csrf_meta_tags %>  
    <meta name="viewport" content="width=device-width, initial-scale=1.0"></head>

  <body>

    <!-- Jumbotron -->  
    <div class="jumbotron masthead">
      <h1>Have something you want to fund?</h1>
      <p>Engage with students and alumni to fund it</p>
    </div>

    <!-- Marketing -->  
    <div class="container">
      <div class="marketing"
        <center>
        <h1>How it works</h1>
      </center>
      <div class='row-fluid'>
        <div class="span4">
          <img class="marketing-img" src="http://s3.amazonaws.com/tententen/images/causes/063355-green-grunge-clipart-icon-people-things-hand-shuffle.png">  
          <h2>1) You post a 'cause'</h2>
          <p>Are you raising funds to help pay for tuition? Start a new business? Organize an event?</p>
        </div>

        <div class="span4">
          <img class="marketing-img" src="http://i.telegraph.co.uk/multimedia/archive/01688/crowd_1688541c.jpg">  
          <h2>2) Students and alumni view your proposal</h2>
          <p>If they like what they see, they can make a contribution.</p>
        </div>

        <div class="span4">
          <img class="marketing-img" src="http://cdn1.iconfinder.com/data/icons/customicondesignoffice2/256/success.png">  
          <h2>3) Funds are transferred to your account</h2>
          <p>We transfer the funds to your account and you make the cause happen.</p>
        </div>
      </div>



      <!-- CTA -->      
      <div class="cta">
        <!-- <img src="assets/images/satisfaction.png" width="250">      
        -->
        <div class="cta-body"></div>
        <div style="clear:both"></div>
        <div class="reserve-body" style="text-align:center">
          <h2>
            Open to Williams alumni and students. Request and invitation.
          </h2>
          <form id="reserve_form" class="form">
            <input type="email" name="email" placeholder="Your email address" class>      

            <input type="text" name="name" placeholder="Your name" class>      
            <input type="submit" class="button" value="Request an invitation"></form>
          <p id="error">
            Blast! There's a problem with our form. Please let us know via
            <a href="mailto:08tqn@williams.edu">email!</a>
          </p>
        </div>
</div>


      <!-- Footer Line -->  
      <hr class="soften">

    </body>
    </html>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Email:</b>
  <%= @student.email %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>